//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuggestedHotel
    {
        public int HotelId { get; set; }
        public string HotelName { get; set; }
        public string Hotellocation { get; set; }
        public string ContactNo { get; set; }
        public int rating { get; set; }
    }
}
